# Generated by Django 5.2 on 2026-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MentionSpike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="GLOBALEVENTID from BigQuery events",
                        max_length=50,
                    ),
                ),
                (
                    "spike_date",
                    models.DateField(
                        db_index=True, help_text="Date when spike occurred"
                    ),
                ),
                (
                    "mention_count",
                    models.IntegerField(help_text="Actual mention count on spike date"),
                ),
                (
                    "baseline_avg",
                    models.FloatField(help_text="7-day rolling average of mentions"),
                ),
                (
                    "baseline_stddev",
                    models.FloatField(
                        help_text="7-day rolling standard deviation of mentions"
                    ),
                ),
                (
                    "z_score",
                    models.FloatField(
                        db_index=True,
                        help_text="Statistical significance: (count - avg) / stddev",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("MEDIUM", "Medium (z >= 2.0)"),
                            ("HIGH", "High (z >= 3.0)"),
                            ("CRITICAL", "Critical (z >= 4.0)"),
                        ],
                        help_text="Spike confidence level",
                        max_length=10,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When spike was detected and recorded",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mention Spike",
                "verbose_name_plural": "Mention Spikes",
                "indexes": [
                    models.Index(
                        fields=["spike_date", "-z_score"], name="spike_date_zscore_idx"
                    ),
                    models.Index(
                        fields=["confidence_level", "spike_date"],
                        name="confidence_date_idx",
                    ),
                ],
                "unique_together": {("event_id", "spike_date")},
            },
        ),
    ]
