# Generated by Django 5.2 on 2026-01-10 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for canonical entity",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "primary_name",
                    models.CharField(
                        db_index=True,
                        help_text="Primary/canonical name for this entity",
                        max_length=255,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("government", "Government"),
                            ("location", "Location"),
                        ],
                        help_text="Type of entity",
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code for geographic filtering",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for additional entity data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this canonical entity was created",
                    ),
                ),
                (
                    "last_verified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this entity record was updated/verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canonical Entity",
                "verbose_name_plural": "Canonical Entities",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "country_code"],
                        name="entity_type_country_idx",
                    ),
                    models.Index(fields=["primary_name"], name="primary_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        db_index=True,
                        help_text="The actual name variant/alias",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gdelt", "GDELT"),
                            ("google_trends", "Google Trends"),
                            ("sec_edgar", "SEC EDGAR"),
                            ("world_bank", "World Bank"),
                        ],
                        help_text="Data source where this alias was found",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        db_index=True,
                        help_text="Splink match_probability (0.0-1.0) or 1.0 for exact matches",
                    ),
                ),
                (
                    "resolution_method",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("splink", "Splink Probabilistic"),
                            ("llm", "LLM Disambiguation"),
                        ],
                        help_text="Method used to resolve this alias to canonical entity",
                        max_length=10,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this alias was first encountered",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Most recent encounter of this alias"
                    ),
                ),
                (
                    "canonical_entity",
                    models.ForeignKey(
                        help_text="The canonical entity this alias refers to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="data_pipeline.canonicalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Alias",
                "verbose_name_plural": "Entity Aliases",
                "indexes": [
                    models.Index(fields=["alias"], name="alias_idx"),
                    models.Index(
                        fields=["canonical_entity", "source"],
                        name="canonical_source_idx",
                    ),
                    models.Index(fields=["confidence"], name="confidence_idx"),
                ],
                "unique_together": {("alias", "source")},
            },
        ),
    ]
