# Generated by Django 5.2 on 2026-01-10 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_entity_entitymention"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_data",
                    models.JSONField(
                        help_text="Forecast points with ds, yhat, yhat_lower, yhat_upper"
                    ),
                ),
                (
                    "dimensional_forecasts",
                    models.JSONField(
                        blank=True,
                        help_text="Dimensional breakdowns (sanctions, political, economic)",
                        null=True,
                    ),
                ),
                ("horizon_days", models.IntegerField(default=30)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text="Vertex AI model resource name",
                        max_length=255,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "forecasting_forecastresult",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "-generated_at"],
                        name="forecasting_entity__48425a_idx",
                    )
                ],
            },
        ),
    ]
