#!/bin/bash
#
# GCP Cutover Script - Phase 18-03
#
# This script documents the manual cutover steps from Celery/Redis to GCP-native
# task execution (Cloud Scheduler + Cloud Functions + Cloud Run + Cloud Tasks).
#
# IMPORTANT: This is a MANUAL cutover checklist, not an automated script.
# Each step requires verification before proceeding.
#
# Prerequisites:
# - Phase 18-01 infrastructure deployed (Cloud Scheduler jobs, Cloud Functions)
# - Phase 18-02 infrastructure deployed (Pub/Sub topics, Cloud Run handlers)
# - Database migrations completed
# - 48-hour validation window scheduled
#

set -euo pipefail

PROJECT_ID="${GCP_PROJECT_ID:-venezuelawatch-staging}"
REGION="${GCP_REGION:-us-central1}"

echo "=========================================="
echo "VenezuelaWatch GCP Cutover - Phase 18-03"
echo "=========================================="
echo ""
echo "Project: $PROJECT_ID"
echo "Region: $REGION"
echo ""
echo "WARNING: This is a MANUAL cutover process."
echo "Do NOT run this script unattended."
echo ""

# ============================================================================
# STEP 1: Disable Celery Beat
# ============================================================================
echo "STEP 1: Disable Celery Beat"
echo "-------------------------------------------"
echo "Status: COMPLETED (settings.py updated)"
echo ""
echo "Verification:"
echo "  - CELERY_BEAT_SCHEDULE = {} in backend/venezuelawatch/settings.py"
echo "  - No periodic tasks will be scheduled"
echo "  - Existing Celery workers can still process queued tasks"
echo ""
echo "Action: Stop celery beat process on production server"
echo "  $ supervisorctl stop celerybeat  # or equivalent"
echo ""
read -p "Press Enter to continue..."
echo ""

# ============================================================================
# STEP 2: Deploy Django to Cloud Run
# ============================================================================
echo "STEP 2: Deploy Django Application to Cloud Run"
echo "-------------------------------------------"
echo "This step deploys the updated Django codebase (without Celery dependencies)"
echo "to Cloud Run, replacing the existing deployment."
echo ""
echo "Commands:"
echo ""
echo "  cd backend"
echo "  gcloud run deploy venezuelawatch-api \\"
echo "    --source . \\"
echo "    --region $REGION \\"
echo "    --platform managed \\"
echo "    --allow-unauthenticated \\"
echo "    --set-env-vars=\"GCP_PROJECT_ID=$PROJECT_ID\" \\"
echo "    --set-env-vars=\"BIGQUERY_DATASET=venezuelawatch_analytics\" \\"
echo "    --set-cloudsql-instances=\"$PROJECT_ID:$REGION:venezuelawatch-db\" \\"
echo "    --service-account=venezuelawatch-api@$PROJECT_ID.iam.gserviceaccount.com"
echo ""
echo "Verification:"
echo "  - Service deploys successfully"
echo "  - Health check endpoint returns 200 OK"
echo "  - No Celery import errors in logs"
echo ""
read -p "Press Enter when deployment is complete..."
echo ""

# ============================================================================
# STEP 3: Run Infrastructure Setup Scripts
# ============================================================================
echo "STEP 3: Run Infrastructure Setup Scripts"
echo "-------------------------------------------"
echo "Execute the infrastructure setup scripts from Phase 18-01 and 18-02."
echo ""
echo "Commands:"
echo ""
echo "  # Phase 18-01: Cloud Scheduler + Cloud Functions"
echo "  cd infrastructure/phase-18-01"
echo "  bash setup_cloud_scheduler.sh"
echo "  bash deploy_cloud_functions.sh"
echo ""
echo "  # Phase 18-02: Pub/Sub + Cloud Run handlers"
echo "  cd ../phase-18-02"
echo "  bash setup_pubsub.sh"
echo "  bash setup_cloud_tasks.sh"
echo ""
echo "Verification:"
echo "  - All Cloud Scheduler jobs exist and are ENABLED"
echo "  - All Cloud Functions deployed successfully"
echo "  - All Pub/Sub topics and subscriptions created"
echo "  - Cloud Run internal API endpoints responding"
echo ""
read -p "Press Enter when infrastructure is ready..."
echo ""

# ============================================================================
# STEP 4: Enable Cloud Scheduler Jobs
# ============================================================================
echo "STEP 4: Enable Cloud Scheduler Jobs"
echo "-------------------------------------------"
echo "Enable periodic task execution via Cloud Scheduler."
echo ""
echo "Jobs to enable:"
echo "  1. gdelt-sync (every 15 minutes)"
echo "  2. reliefweb-updates (daily)"
echo "  3. fred-series-sync (daily)"
echo "  4. comtrade-sync (monthly)"
echo "  5. worldbank-sync (quarterly)"
echo "  6. sanctions-screening (daily at 4 AM UTC)"
echo ""
echo "Commands:"
echo ""
echo "  gcloud scheduler jobs list --location=$REGION"
echo "  gcloud scheduler jobs resume gdelt-sync --location=$REGION"
echo "  gcloud scheduler jobs resume reliefweb-updates --location=$REGION"
echo "  gcloud scheduler jobs resume fred-series-sync --location=$REGION"
echo "  gcloud scheduler jobs resume comtrade-sync --location=$REGION"
echo "  gcloud scheduler jobs resume worldbank-sync --location=$REGION"
echo "  gcloud scheduler jobs resume sanctions-screening --location=$REGION"
echo ""
echo "Verification:"
echo "  - All jobs show STATE=ENABLED"
echo "  - Next scheduled run times are correct"
echo ""
read -p "Press Enter when jobs are enabled..."
echo ""

# ============================================================================
# STEP 5: Monitor for 48 Hours
# ============================================================================
echo "STEP 5: Monitor for 48 Hours"
echo "-------------------------------------------"
echo "Monitor all GCP services for 48 hours before completing cutover."
echo ""
echo "Monitoring checklist:"
echo ""
echo "1. Cloud Scheduler Jobs"
echo "   - Verify jobs execute on schedule"
echo "   - Check for job failures"
echo "   Command: gcloud scheduler jobs list --location=$REGION"
echo ""
echo "2. Cloud Functions"
echo "   - Monitor execution logs"
echo "   - Check error rates"
echo "   Command: gcloud functions logs read --region=$REGION"
echo ""
echo "3. Pub/Sub Topics"
echo "   - Verify message delivery"
echo "   - Check for message backlogs"
echo "   Command: gcloud pubsub topics list"
echo ""
echo "4. Cloud Run Services"
echo "   - Monitor request latency"
echo "   - Check error rates"
echo "   Command: gcloud run services list --region=$REGION"
echo ""
echo "5. BigQuery Dataset"
echo "   - Verify data ingestion continues"
echo "   - Check for data quality issues"
echo "   Command: bq ls $PROJECT_ID:venezuelawatch_analytics"
echo ""
echo "6. Cloud Tasks Queues"
echo "   - Monitor task execution"
echo "   - Check for task failures"
echo "   Command: gcloud tasks queues list --location=$REGION"
echo ""
echo "Success criteria:"
echo "  - All periodic tasks execute successfully"
echo "  - No increase in error rates"
echo "  - Data pipeline operates normally"
echo "  - No manual intervention required"
echo ""
read -p "Press Enter to continue to rollback instructions..."
echo ""

# ============================================================================
# ROLLBACK INSTRUCTIONS
# ============================================================================
echo "=========================================="
echo "ROLLBACK INSTRUCTIONS"
echo "=========================================="
echo ""
echo "If issues occur during the 48-hour monitoring period:"
echo ""
echo "1. Pause Cloud Scheduler Jobs"
echo "   gcloud scheduler jobs pause gdelt-sync --location=$REGION"
echo "   gcloud scheduler jobs pause reliefweb-updates --location=$REGION"
echo "   gcloud scheduler jobs pause fred-series-sync --location=$REGION"
echo "   gcloud scheduler jobs pause comtrade-sync --location=$REGION"
echo "   gcloud scheduler jobs pause worldbank-sync --location=$REGION"
echo "   gcloud scheduler jobs pause sanctions-screening --location=$REGION"
echo ""
echo "2. Restore Celery Configuration"
echo "   git revert <this-commit>"
echo "   git checkout <previous-commit> backend/requirements.txt"
echo ""
echo "3. Reinstall Celery Dependencies"
echo "   cd backend"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Restart Celery Workers and Beat"
echo "   supervisorctl restart celery celerybeat  # or equivalent"
echo ""
echo "5. Verify Celery Tasks Resume"
echo "   - Check Celery logs for task execution"
echo "   - Verify periodic tasks run on schedule"
echo ""
echo "6. Deploy Previous Django Version"
echo "   gcloud run deploy venezuelawatch-api \\"
echo "     --image=<previous-image> \\"
echo "     --region=$REGION"
echo ""
echo "=========================================="
echo "Cutover Preparation Complete"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Execute STEP 2 (Deploy Django to Cloud Run)"
echo "  2. Execute STEP 3 (Run infrastructure setup scripts)"
echo "  3. Execute STEP 4 (Enable Cloud Scheduler jobs)"
echo "  4. Begin 48-hour monitoring period (STEP 5)"
echo ""
echo "After 48 hours of successful operation:"
echo "  - Mark Phase 18-03 as complete"
echo "  - Proceed with Task 2 (remove Celery dependencies)"
echo "  - Decommission Redis/Celery infrastructure"
echo ""
