# Generated by Django 5.2 on 2026-01-08 22:12

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Data source: GDELT, FRED, UN_COMTRADE, WORLD_BANK, RELIEFWEB, USITC, PORT_AUTHORITIES",
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Category: POLITICAL, ECONOMIC, TRADE, NATURAL_RESOURCE, TARIFF, DISASTER, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Event occurrence time (UTC)",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "content",
                    models.JSONField(
                        help_text="Flexible event data structure varying by source"
                    ),
                ),
                (
                    "entities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Extracted entities: people, companies, governments",
                        size=None,
                    ),
                ),
                (
                    "sentiment",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score from -1 (negative) to 1 (positive)",
                        null=True,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        blank=True,
                        db_index=True,
                        help_text="Computed risk level (0-100)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "source"],
                        name="events_timesta_582f82_idx",
                    ),
                    models.Index(
                        fields=["-timestamp", "event_type"],
                        name="events_timesta_4c884f_idx",
                    ),
                    models.Index(
                        fields=["-timestamp", "risk_score"],
                        name="events_timesta_fda6d3_idx",
                    ),
                ],
            },
        ),
    ]
