# Generated by Django 5.2 on 2026-01-09 02:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Detected language code (ISO 639-1: en, es, ar, pt, etc.)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="llm_analysis",
            field=models.JSONField(
                blank=True,
                help_text="Complete LLM analysis results (for debugging and reference)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="relationships",
            field=models.JSONField(
                blank=True,
                help_text="Entity relationships extracted by LLM (subject-predicate-object triples)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated concise summary (1-2 sentences)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Thematic topics identified by LLM",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="urgency",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Urgency level: low, medium, high, immediate",
                max_length=20,
                null=True,
            ),
        ),
    ]
