# Generated by Django 5.2 on 2026-01-09 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_llm_intelligence_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionsMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Name matched from event's extracted entities",
                        max_length=200,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity: person, organization", max_length=50
                    ),
                ),
                (
                    "sanctions_list",
                    models.CharField(
                        help_text="Source sanctions list: OFAC-SDN, UN-1267, EU-SANCTIONS, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="Fuzzy match confidence score (0.0-1.0)"
                    ),
                ),
                (
                    "sanctions_data",
                    models.JSONField(
                        help_text="Complete API response with aliases, dates, programs, etc."
                    ),
                ),
                (
                    "sanctions_checked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this sanctions check was performed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event containing the sanctioned entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions_matches",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "db_table": "sanctions_matches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "-match_score"],
                        name="sanctions_m_event_i_0767d3_idx",
                    ),
                    models.Index(
                        fields=["-sanctions_checked_at"],
                        name="sanctions_m_sanctio_12b975_idx",
                    ),
                ],
            },
        ),
    ]
