# Generated by Django 5.2 on 2026-01-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sanctionsmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEV1_CRITICAL", "SEV1 - Critical"),
                    ("SEV2_HIGH", "SEV2 - High"),
                    ("SEV3_MEDIUM", "SEV3 - Medium"),
                    ("SEV4_LOW", "SEV4 - Low"),
                    ("SEV5_MINIMAL", "SEV5 - Minimal"),
                ],
                db_index=True,
                help_text="Event severity classification (SEV1=Critical to SEV5=Minimal)",
                max_length=20,
                null=True,
            ),
        ),
    ]
