# Generated by Django 5.2 on 2026-01-09 06:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_severity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized/deduplicated entity name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("ORGANIZATION", "Organization"),
                            ("GOVERNMENT", "Government Agency"),
                            ("LOCATION", "Location"),
                        ],
                        db_index=True,
                        help_text="Type of entity",
                        max_length=20,
                    ),
                ),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        default=list,
                        help_text="Known name variations (e.g., ['N. Maduro', 'President Maduro'])",
                        size=None,
                    ),
                ),
                ("first_seen", models.DateTimeField(db_index=True)),
                ("last_seen", models.DateTimeField(db_index=True)),
                ("mention_count", models.IntegerField(db_index=True, default=0)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional information (roles, descriptions, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "entities",
                "ordering": ["-mention_count", "-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["-mention_count"], name="entities_mention_39e1bf_idx"
                    ),
                    models.Index(
                        fields=["-last_seen"], name="entities_last_se_fc593e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_name",
                    models.CharField(
                        help_text="Exact text as it appeared in event", max_length=200
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(
                        help_text="Fuzzy match confidence score (0.0-1.0)"
                    ),
                ),
                (
                    "relevance",
                    models.FloatField(
                        blank=True,
                        help_text="LLM relevance score if available",
                        null=True,
                    ),
                ),
                (
                    "mentioned_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Denormalized from event.timestamp for trending queries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="core.entity",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mentions",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "db_table": "entity_mentions",
                "indexes": [
                    models.Index(
                        fields=["-mentioned_at"], name="entity_ment_mention_467167_idx"
                    ),
                    models.Index(
                        fields=["entity", "-mentioned_at"],
                        name="entity_ment_entity__558303_idx",
                    ),
                ],
                "unique_together": {("entity", "event", "raw_name")},
            },
        ),
    ]
